spring:
  application:
   name: config-server-github

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:2001/eureka
